### PR TITLE
test(io-context): add detail in assert error message

### LINKED ISSUE #103: test: flaky test
We had that failing test: https://github.com/holepunchto/bare-ffmpeg/blob/main/test/io-context.js#L34

CI Error: https://github.com/holepunchto/bare-ffmpeg/actions/runs/17071613875/job/48401784644

It disappeared as it came. Lets keep it in the radar.

### PR DESCRIPTION
**Pull request by tony-go**
Aiming to resolve #103 !

### CODE REVIEW

File: test/io-context.js [hunk 1]
```diff
@@ -41,8 +49,8 @@ test('IOContext streaming mp4 with onseek', (t) => {
     onread: (buffer) => {
       const bytesToRead = Math.min(buffer.length, data.length - offset)
 
-      if (bytesToRead === 0) {
-        return 0
```
Comment (tony-go) [inline test/io-context.js:45]: Did not want that
